const booksData = [
    {
        id: 1,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        genre: "Classic",
        image: "book1.jpg",
        description: "To Kill a Mockingbird is a novel by Harper Lee published in 1960. It is a classic of American literature and widely read in high schools and universities. The story explores racial injustice and the loss of innocence in the 1930s American South.",
    },
    {
        id: 2,
        title: "1984",
        author: "George Orwell",
        genre: "Dystopian",
        image: "book2.jpg",
        description: "1984 is a dystopian novel by George Orwell published in 1949. The story is set in a totalitarian society where Big Brother, the Party leader, exercises complete control over every aspect of people's lives. The novel explores themes of government surveillance, oppression, and the power of language.",
    },
    {
        id: 3,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Literary Fiction",
        image: "book3.jpg",
        description: "The Great Gatsby is a novel by F. Scott Fitzgerald published in 1925. Set during the Roaring Twenties, it follows the enigmatic millionaire Jay Gatsby and his obsession with the beautiful Daisy Buchanan. The novel explores themes of wealth, love, and the corruption of the American Dream.",
    },
    {
        id: 4,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "Romance",
        image: "book4.jpg",
        description: "Pride and Prejudice is a novel by Jane Austen published in 1813. It tells the story of Elizabeth Bennet, who navigates issues of manners, upbringing, morality, education, and marriage in the society of the landed gentry in early 19th-century England. The novel is widely considered one of the greatest works of romantic fiction.",
    },
    {
        id: 5,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        genre: "Coming-of-Age",
        image: "book5.jpg",
        description: "The Catcher in the Rye is a novel by J.D. Salinger published in 1951. It follows the story of Holden Caulfield, a disaffected teenager who leaves his boarding school and embarks on a journey through New York City. The novel explores themes of teenage angst, alienation, and the loss of innocence.",
    },
    {
        id: 6,
        title: "Moby-Dick",
        author: "Herman Melville",
        genre: "Adventure",
        image: "book1.jpg",
        description: "Moby-Dick is an epic novel by Herman Melville published in 1851. It tells the story of Captain Ahab's relentless pursuit of the white whale Moby Dick. The novel explores themes of obsession, fate, and the nature of evil.",
    },
    {
        id: 7,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        image: "book2.jpg",
        description: "The Hobbit is a fantasy novel by J.R.R. Tolkien published in 1937. It follows the adventure of Bilbo Baggins, a hobbit who is swept into a quest to reclaim the lost dwarf kingdom of Erebor from the dragon Smaug. The novel is set in Tolkien's Middle-earth and serves as a prelude to The Lord of the Rings.",
    },
    {
        id: 8,
        title: "Frankenstein",
        author: "Mary Shelley",
        genre: "Gothic",
        image: "book3.jpg",
        description: "Frankenstein; or, The Modern Prometheus is a novel by Mary Shelley published in 1818. It tells the story of Victor Frankenstein, a young scientist who creates a grotesque creature in an unorthodox scientific experiment. The novel explores themes of ambition, creation, and the consequences of playing god.",
    },
    {
        id: 9,
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        genre: "Gothic",
        image: "book4.jpg",
        description: "Jane Eyre is a novel by Charlotte Brontë published in 1847. It follows the story of Jane Eyre, an orphan who becomes a governess and falls in love with her employer, Mr. Rochester. The novel explores themes of love, social class, and the search for identity.",
    },
    {
        id: 10,
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        genre: "Fantasy",
        image: "book5.jpg",
        description: "The Lord of the Rings is an epic fantasy trilogy by J.R.R. Tolkien published between 1954 and 1955. It follows the journey of Frodo Baggins to destroy the One Ring and defeat the Dark Lord Sauron. The trilogy explores themes of power, friendship, and the battle between good and evil.",
    },
    // Add more books as needed
];

export default booksData;
